export const FETCH_HEROES_START = 'FETCH_HEROES_START';
export const FETCH_HEROES_FAIL = 'FETCH_HEROES_FAIL';
export const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS';
export const FETCH_HEROES = 'FETCH_HEROES';

export const FETCH_PUBLIC_MATCHES_START = 'FETCH_PUBLIC_MATCHES_START';
export const FETCH_PUBLIC_MATCHES_FAIL = 'FETCH_PUBLIC_MATCHES_FAIL';
export const FETCH_PUBLIC_MATCHES_SUCCESS = 'FETCH_PUBLIC_MATCHES_SUCCESS'; 
export const FETCH_PUBLIC_MATCHES = 'FETCH_PUBLIC_MATCHES';


export const FETCH_PUBLIC_MATCH = 'FETCH_PUBLIC_MATCH';
export const FETCH_PUBLIC_MATCH_START = 'FETCH_PUBLIC_MATCH_START';
export const FETCH_PUBLIC_MATCH_FAIL = 'FETCH_PUBLIC_MATCH_FAIL';
export const FETCH_PUBLIC_MATCH_SUCCESS = 'FETCH_PUBLIC_MATCH_SUCCESS';

export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';
export const FETCH_ITEMS_SUCCESS = 'FETH_ITEMS_SUCCESS';
export const FETCH_ITEMS = 'FETCH_ITEMS';

export const GAME_START = 'GAME_START';
export const GAME_END = 'GAME_END'; 